version: "3.7"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./docktypeData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= MSMoon
    ports:
      - 27017:27017
